version: "3.9"

services:
  form_backend:
    build: .
    command: python flask_backend.py
    env_file: .env
    ports:
      - "6000:6000"
    volumes:
      - ./users.db:/app/data/submissions.db
      - ./static:/app/static
      - ./templates:/app/templates
    restart: always